export const GLOSSARY: Record<string, { short: string; long: string }> = {
  asymptote: { short: 'What one noise term alone would draw on the plot', long: 'Each dashed line is one noise coefficient by itself — the ADEV that term alone would produce. The dotted line is all of them combined. Where the solid measured curve hugs a dashed line, that noise dominates at that averaging time. The corners between dashed lines are where one noise hands over to the next. That is how you read coefficients off a measured plot. Formulas: √3·Q/τ, N/√τ, 0.664·B (flat), K·√(τ/3), R·τ/√2.' },
  ADEV: { short: 'Allan deviation: how noisy the device is at each averaging time', long: 'Take the rate signal. Average it in windows of length τ. The Allan deviation is the typical difference between one window and the next. Short τ shows fast noise; long τ shows slow wander. On a log-log plot every noise type is a straight line with its own slope, so one curve summarizes the whole noise character of a device. It describes the rate, not the accumulated error — the Error growth tab does that.' },
  MDEV: { short: 'A variant that tells white phase noise from flicker phase noise', long: 'On an ordinary ADEV plot, white phase noise and flicker phase noise look the same: both fall as 1/τ. The modified Allan deviation averages phase inside each window first, and that splits them: white phase falls as τ^-3/2, flicker phase as 1/τ. Use it when the short-τ end of your plot slopes at -1 and you need to know which of the two you have — measurement-chain noise or the device itself.' },
  HDEV: { short: 'A variant that is blind to steady drift', long: 'A drifting clock (rubidium, anything that ages) buries its long-τ noise under the drift on an ADEV plot. The Hadamard deviation uses second differences of frequency, which cancels a steady drift exactly, so you can read the random noise underneath. GPS operations budget in Hadamard for exactly this reason.' },
  Q: { short: 'White noise added directly to the output (quantization)', long: 'Q is white noise sitting directly on the integrated output — angle for a gyro, time for a clock. It comes from quantization and readout. It does not accumulate: its contribution to the error budget is bounded at Q, no matter how long you wait. On the ADEV plot it is the steep 1/τ line at short τ (height √3·Q/τ).' },
  F: { short: 'Flicker (1/f) phase noise', long: 'F is flicker (1/f) noise on the phase. On an ADEV plot it looks identical to Q — both fall as roughly 1/τ — which is the whole reason MDEV exists. It is rarely a datasheet number; it is here so you can see the MDEV separation work.' },
  N: { short: 'White rate noise — angle random walk for gyros', long: 'N is white noise on the rate itself. It is the most-quoted datasheet number: angle random walk (°/√h) for gyros, σy(1 s) for clocks. On the ADEV plot it is the 1/√τ line, and N is the value at τ = 1 s. Integrated, it makes the error grow as N·√t — fast at first, slower later.' },
  B: { short: 'Bias instability, a.k.a. flicker frequency noise — the flicker floor of the ADEV plot at 0.664·B', long: 'B is the slow random wander of the bias during a run: flicker (1/f) noise on the rate. Three names for one thing — bias instability on a datasheet, flicker frequency noise in the noise-type list, the flicker floor on a plot. It is the flat floor of the ADEV plot, at height 0.664·B. You cannot calibrate it out, because it never settles. Once fixes stop, it grows the error as roughly B·t, which makes it the dominant term for outages longer than a few minutes on most devices. No simple filter model captures flicker exactly — that is what the estimate methods are about.' },
  K: { short: 'Rate random walk — random-walk frequency noise on the clock side; the bias goes for a walk', long: 'K is white noise on the derivative of the bias, so the bias itself wanders off like a random walk. Inertial datasheets call it rate random walk; clock people call the same thing random-walk frequency noise. On the ADEV plot it is the rising √τ line at long τ (height K·√(τ/3)). Integrated twice, it grows the error as K·t^1.5/√3. It is the process-noise term a 2-state Kalman filter carries on its bias state.' },
  D: { short: 'Random walk of the drift rate (3-state devices)', long: 'D puts white noise on the drift rate itself — the aging rate of a clock wanders. The Allan variance does not even converge for this noise: a D-only device\'s ADEV keeps growing with record length and has no fixed slope, so no asymptote is drawn for it. HDEV handles it. D is usually tiny; what matters over months is its cousin, the uncertainty in the initial drift rate.' },
  R: { short: 'Steady drift: clock aging, gyro rate ramp', long: 'R is a deterministic, steady change of the rate with time. Left alone it grows the error as R·t²/2. Because it is deterministic, it can be estimated and removed. Compensating a drift means estimating it, and the estimate needs a home: a model state that means "drift rate". A 3-state model has one, so the tool treats the nominal aging as subtracted and budgets only your uncertainty in it (drift-rate uncertainty). A 2-state model (error, bias) has no drift state — nothing estimates R, nothing subtracts it, and the full R·t²/2 lands in the error.' },
  turnOnBias: { short: 'A different constant offset every power-up', long: 'Turn-on bias is a new constant offset each time the device powers on. It is not noise: the first few external fixes estimate it, and it is effectively gone before any outage starts. What survives is the small leftover uncertainty, which is the starting point of the error-growth curve. Do not confuse it with bias instability, which keeps wandering during the run.' },
  thermal: { short: 'Bias shift caused by temperature change', long: 'Temperature coefficient times temperature change equals bias shift. The device temperature follows the environment through a lag (thermal mass). An ADEV measured on a constant-temperature bench never shows this, and the budget formulas never include it — so it is shown as its own line, carried only by the simulated truth. If it dominates, you need thermal control or compensation, not a better device.' },
  Bayard: { short: 'The closed-form error-growth formula this tool uses', long: 'Bayard (JPL, 2000) wrote down exactly how the error covariance grows after the last external fix, for white rate noise plus a random-walk bias: P(t) = p11 + 2·p12·t + p22·t² + q1·t + q2·t³/3, starting from the steady-state post-fix covariance. It is exact for those two noises and has no term at all for flicker — which is why the estimate methods exist.' },
  fix: { short: 'How good and how frequent the external measurement was', long: 'Before the outage, something external (star tracker, GPS pulse) was correcting the device. Its 1σ accuracy and its cadence set the starting error when fixes stop — better or more frequent fixes lower the starting point. They do nothing about the growth rate afterward; that belongs to the device.' },
  requirement: { short: 'The error you are allowed at a given time, at a given confidence', long: 'A requirement is three numbers: an error value, a sigma level, and a duration — for example 1° at 3σ after 600 s. Every tab reports margin against the active requirement. The most useful single number at PDR is the ratio of simulated truth to the formula at that duration: it says how optimistic your budget method is for this device.' },
  Tm: { short: 'The one timescale where a flicker approximation is exact', long: 'Flicker noise has no exact filter model, so every approximation picks one timescale T_m where it is pinned to the true flicker floor. Near T_m the approximation is honest; away from it, it drifts. T_m defaults to the active requirement\'s duration, which is the honest choice. Change it to see how sensitive an inherited analysis was to someone else\'s arbitrary pick (Bayard used 1 hour).' },
  fudge: { short: 'Flicker fed into the formula as random walk — wrong shape, adjustable size', long: 'The classic trick: convert bias instability into a random-walk coefficient sized to match the flicker floor at T_m (q2 = B²/T_m). The resulting error grows as t^1.5, but real flicker grows as t — so for durations shorter than about 3·T_m the fudge is optimistic (about 4× at 10 minutes with a 1-hour T_m), and beyond that it is conservative. Defensible only as a bound, with T_m no larger than a third of your duration.' },
  constant: { short: 'Treat the bias as an unknown constant of size B', long: 'Assume the bias is some fixed unknown number with standard deviation B. The error then grows as B·t — the right shape and about the right size for flicker over minutes to hours. For an open-loop outage budget this is the honest single-term estimate. It is a poor model to run inside a live filter, which would eventually convince itself it knows the constant perfectly.' },
  gm: { short: 'Bias as an exponentially-forgetting process', long: 'The IEEE-952 default: a bias that wanders but forgets its past over a correlation time T_m. Below T_m it behaves like the constant model. Beyond T_m it forgets too much: the error grows only as √t, slower than real flicker, so it turns quietly optimistic for long durations. Its virtue is for running filters — bounded variance with live process noise keeps a filter healthy.' },
  fittedK: { short: 'Use only the measured random-walk line; ignore the floor', long: 'If the long-τ end of the ADEV has turned up into a √τ line, fit K directly from it — no fudge needed. Exact for the random-walk part, silent about the flicker floor, so it is optimistic across the whole flat region. Combine it with the constant model to cover both.' },
  gmSum: { short: 'Flicker built from several forgetting processes', long: 'A sum of Gauss-Markov processes with correlation times a decade apart imitates 1/f noise over that band. This is what a filter designer who needs a Markov flicker model actually builds. Switch the truth generator to it to see where the imitation departs from real flicker outside its band.' },
  DMTD: { short: 'How two good clocks are compared: mix both against a third', long: 'Both clocks are mixed against a common offset oscillator tuned a few hertz away, and the slow beat notes are timed. The offset oscillator is common to both channels, so its noise cancels in the difference — which is why a cheap oscillator can referee two atomic clocks. What is left is the electronics floor and whatever fails to cancel.' },
  leak: { short: 'The fraction of offset-oscillator noise that fails to cancel', long: 'The two DMTD channels are never perfectly identical, so a small fraction ε of the offset oscillator\'s noise survives into the measurement. At ε = 0 the offset oscillator is invisible. At ε = 0.01 a poor one reappears at long τ. This knob is the difference between "the OCXO does not matter" and "the OCXO matters".' },
  floor: { short: 'The electronics noise limit of the measurement', long: 'Mixers, detectors, and counters add white phase noise at the picosecond level. On the measured ADEV it is a 1/τ line at short τ, and nothing below it can be seen. If the floor sits above the clocks you are comparing, you are measuring your electronics, not your clocks.' },
  crossover: { short: 'Where one clock becomes noisier than the other', long: 'Where two clocks\' ADEV curves cross, they swap roles: below that τ one is quieter, above it the other is. That is the natural handoff point. A disciplined clock (GPSDO, steered RAFS) exploits it, trusting the steering source at long τ and its own oscillator at short τ, and the combination roughly follows the lower of the two curves. Once the steering stops, holdover error grows from that point.' },
  knee: { short: 'Where a better device stops buying you anything', long: 'With periodic fixes, the steady-state error depends on both device noise and fix quality. Past some device grade, the error is fix-limited: a better device buys nothing. Conversely, for a given device there is a slowest fix cadence that still meets the requirement. That trade — device grade against fix duty cycle — is the PDR decision this chart shows.' },
  percentile: { short: 'The simulated "3σ" is a percentile, not 3 × a standard deviation', long: 'The envelope takes the absolute error across all simulated runs and reads the 99.7th percentile directly (or 95.5th, or 68th, matching the requirement\'s sigma level). Multiplying a standard deviation by 3 assumes the errors are Gaussian; flicker\'s accumulated error is not. Percentiles stay honest either way.' },
  confidence: { short: 'How trustworthy each measured ADEV point is', long: 'Every ADEV point is estimated from a finite record. Long-τ points come from only a handful of independent samples, so they scatter. The band shows the ±1σ statistical uncertainty; points beyond a tenth of the record length are drawn faded and should not be read at all.' },
  driftKnowledge: { short: 'How well the drift rate was known at the last sync', long: 'For a 3-state clock, the aging rate is estimated before launch or at the last sync. What enters the budget over months is not the aging itself — that is compensated — but the uncertainty of the estimate. That uncertainty grows the time error as (uncertainty)·t²/2 and usually dominates everything else at month scales. Zero is defensible only for short spans or a very fresh calibration against a better reference — and if the device has any D, perfect knowledge is impossible even in principle, because the drift itself wanders after the last sync.' },
};

export const REQUIRED_TERMS = Object.keys(GLOSSARY);

export function dfn(term: string, text?: string): HTMLElement {
  const g = GLOSSARY[term];
  const el = document.createElement('dfn');
  el.textContent = text ?? term;
  if (!g) return el;
  el.title = g.short;
  let open: HTMLElement | null = null;
  el.addEventListener('click', () => {
    if (open) { open.remove(); open = null; return; }
    open = document.createElement('div'); open.className = 'gloss'; open.textContent = g.long;
    el.insertAdjacentElement('afterend', open);
  });
  return el;
}
