export const GLOSSARY: Record<string, { short: string; long: string }> = {
  ADEV: { short: 'Allan deviation: noise vs averaging time', long: 'The Allan deviation σ(τ) is the RMS difference between successive averages of the rate-like quantity (gyro rate, fractional frequency) over windows of length τ. Plotted log–log, each noise type appears as a straight line with a characteristic slope, so you can read coefficients off the plot. It is computed on rate/frequency data and says nothing directly about the integrated error; that is what the error-growth view is for.' },
  MDEV: { short: 'Modified Allan deviation: separates white from flicker phase noise', long: 'The modified Allan deviation averages the phase over each window before differencing. Its only practical purpose is that white phase noise falls as τ^-3/2 under MDEV while flicker phase noise falls as τ^-1, whereas ordinary ADEV shows both as τ^-1. Use it when the short-τ region of your ADEV plot slopes at -1 and you need to know which of the two it is.' },
  HDEV: { short: 'Hadamard deviation: blind to linear frequency drift', long: 'The Hadamard deviation uses second differences of frequency (third differences of phase) instead of first differences, which cancels a linear frequency drift exactly. Rubidium clocks and anything that ages show drift that would otherwise dominate the long-τ end of an ADEV plot and hide the random-walk region you are trying to read.' },
  Q: { short: 'Quantization / white phase noise coefficient', long: 'Q is the standard deviation of white noise added directly to the integrated quantity (angle for a gyro, time for a clock). Under ADEV it appears as a τ^-1 slope at short τ with σ(τ) = √3·Q/τ. It does not grow with time: its contribution to the error budget is bounded at Q.' },
  F: { short: 'Flicker phase noise coefficient', long: 'F sets the level of 1/f phase noise, which also appears as roughly τ^-1 under ADEV and is indistinguishable from white phase noise there; MDEV separates them. It is included so the MDEV lesson can be shown and is rarely a datasheet number.' },
  N: { short: 'Angle random walk / white frequency noise', long: 'N is the white noise on the rate-like quantity. Under ADEV it is the τ^-1/2 line, σ(τ) = N/√τ, and N is read as the value at τ = 1 s. Integrated, it makes the angle (or time) error grow as N·√t. Gyro datasheets quote it in °/√h; clock datasheets quote σy(1 s).' },
  B: { short: 'Bias instability / flicker frequency noise (the ADEV floor)', long: 'B is the slow, random wander of the bias during a run — 1/f noise on the rate. It is the flat floor of the ADEV plot, at height 0.664·B. It cannot be calibrated out because it never settles, and once external fixes stop the error grows as roughly B·t, which makes it the dominant term for outages longer than a few minutes on most devices. No finite-state filter model represents it exactly; see the estimate methods.' },
  K: { short: 'Rate random walk / random-walk frequency noise', long: 'K is white noise on the *derivative* of the bias, so the bias itself random-walks. Under ADEV it is the τ^+1/2 line at long τ, σ(τ) = K·√(τ/3). Integrated twice it makes the error grow as K·t^3/2/√3. It is the process-noise term a 2-state Kalman filter carries on its bias state.' },
  D: { short: 'Random walk of the drift (3-state devices)', long: 'D is white noise on the second derivative of the rate-like quantity: the frequency drift (aging rate) of a clock, or the rate of change of an accelerometer bias, itself random-walks. The Allan variance does not converge for this noise type (α = −4): a D-only device\'s ADEV keeps growing with record length and has no fixed slope, so there is no attainable ADEV asymptote to draw, and this tool does not draw one. Hadamard deviation is the right tool for this noise type. D is the process noise on the third state of a 3-state model and is usually tiny; its cousin, the *uncertainty in the initial drift rate*, is what matters over months.' },
  R: { short: 'Linear drift / rate ramp', long: 'R is a deterministic linear change of the rate-like quantity with time (clock aging, gyro rate ramp). It appears as a τ^+1 line under ADEV and is removed entirely by HDEV. Integrated, it produces an error of R·t²/2. Because it is deterministic it can be estimated and compensated; what remains in the budget is the uncertainty in that estimate. For a 3-state device (states carrying an explicit drift term) this tool treats the nominal aging as compensated on both the analytic model and the Monte Carlo truth, so R contributes nothing to either — the residual is entirely the drift-rate uncertainty, driftKnowledge. For a 2-state device there is no drift state to hold the compensation, so aging is left unmodelled and appears in full as R·t²/2 in both the estimate and the truth.' },
  turnOnBias: { short: 'Bias repeatability across power-ups', long: 'Turn-on bias is a different constant offset each time the device is powered. It is not noise: a filter estimates it from the first few external fixes, and it is effectively gone before any outage starts. The residual after estimation is the initial bias uncertainty p22 in the Bayard model. Do not confuse it with bias instability, which keeps changing during the run.' },
  thermal: { short: 'Temperature-driven bias shift', long: 'A temperature coefficient times the device temperature deviation adds a deterministic offset to the rate-like quantity. The device temperature follows the ambient through a first-order lag (thermal mass). This is not captured by an ADEV measured at constant temperature, and the analytic estimate never sees it; it is shown separately so you can judge whether thermal control or compensation is needed.' },
  Bayard: { short: 'Analytic open-loop error growth after the last fix', long: 'Bayard (2000) gives the closed-form growth of the attitude covariance after the last star-tracker update, starting from the steady-state post-update covariance and driven by white rate noise q1 = N² and random-walk bias noise q2. P(t) = p11 + 2·p12·t + p22·t² + q1·t + q2·t³/3. The same algebra applies to a clock (time, frequency) and, with a third state, to an accelerometer. It is exact for white + random-walk noise and has no term for flicker.' },
  fix: { short: 'Quality and cadence of the external measurement before the outage', long: 'The last-fix quality is the 1σ accuracy of the external measurement (star-tracker NEA, GPS time sync) and how often it arrived. Bayard uses r = Δ·σ² to compute the steady-state post-fix covariance, which is where the error-growth curve starts. Better or more frequent fixes lower the starting point but do nothing about the growth rate.' },
  requirement: { short: 'Error budget target at a given duration and sigma level', long: 'A requirement is a (value, sigma level, duration) triple: e.g. 1° at 3σ after 600 s. Every view reports margin against the active requirement, and the model timescale defaults to its duration. The useful PDR number is the ratio of Monte Carlo truth to the analytic estimate at that duration: it says how optimistic your budget method is for this device at this timescale.' },
  Tm: { short: 'Model timescale: where an approximation is pinned to the flicker floor', long: 'The estimate methods that approximate flicker each have one free timescale at which they are made to agree with the flicker floor; they are honest near it and wrong away from it. T_m is that single knob (the fudge uses q2 = B²/T_m; the Gauss-Markov uses correlation time T_m). It defaults to the active requirement\'s duration. Change it to see how sensitive an inherited analysis is to an arbitrary choice, or to reproduce one (Bayard used 1 h).' },
  fudge: { short: 'Bias instability fed in as a random walk, q2 = B²/T_m', long: 'The bayard_calc.m mapping: take the datasheet bias instability and treat it as a random-walk coefficient sized to match the flicker floor at T_m. The resulting error grows as t^3/2, the wrong shape: for durations shorter than about 3·T_m it is optimistic by roughly √(t/3T_m) (4× at 10 min with T_m = 1 h), and beyond that it is conservative. Defensible only as a bound with T_m ≤ t/3.' },
  constant: { short: 'Bias instability as an unknown constant, σ = B', long: 'Treat the bias as a random constant with standard deviation B and no process noise. The error then grows as B·t, which is the right shape and about the right size for flicker over minutes to hours (true flicker adds a slow logarithmic factor). For a PDR outage budget this is the honest single-term estimate. It is a poor model for a running filter, because with no process noise the filter would eventually believe it knows the bias perfectly.' },
  gm: { short: 'Bias instability as a first-order Gauss-Markov process', long: 'The IEEE 952 default: an exponentially correlated bias with standard deviation B and correlation time T_m. Below T_m it behaves like the constant model (B·t); above it the bias forgets its past and the error grows only as B·√(2·T_m·t), which is slower than flicker, so it becomes quietly optimistic for long durations. Its virtue is closed-loop: bounded variance with live process noise keeps a filter healthy.' },
  fittedK: { short: 'Use only the measured random-walk coefficient; ignore B', long: 'If the ADEV has turned up into a τ^+1/2 region, K can be fitted there and used directly with no fudge. This is exact for the random-walk part and says nothing about the floor, so it is optimistic across the whole flat region of the ADEV. Combine with the constant model to cover both.' },
  gmSum: { short: 'Flicker approximated by several Gauss-Markov processes', long: 'A sum of first-order Gauss-Markov processes with correlation times spaced a decade apart approximates 1/f noise over that band. This is what a filter designer who needs a Markov model of flicker actually builds. The tool can use it as the *truth* generator instead of exact flicker so you can see where the approximation departs from the real thing outside its band.' },
  DMTD: { short: 'Dual-mixer time-difference measurement', long: 'In a DMTD both clocks are mixed against a common offset oscillator tuned a few hertz away, and the beat-note zero crossings are timed. Because the offset oscillator is common to both channels its noise cancels in the difference, which is why two clocks can be compared far below the offset oscillator\'s own noise. What remains is the measurement floor (mixer, zero-crossing detector, counter) and any imperfect cancellation between the two channels.' },
  leak: { short: 'Fraction of offset-oscillator noise that does not cancel', long: 'The two DMTD channels are never identical, so a fraction ε of the offset oscillator\'s phase noise survives in the measured difference. With ε = 0 the offset oscillator is invisible; at ε = 0.01 a poor offset oscillator reappears at long τ. This is the knob that turns "the OCXO does not matter" into "the OCXO matters".' },
  floor: { short: 'White phase-noise floor of the measurement system', long: 'The DMTD electronics add white phase noise at the picosecond level. It shows as a τ^-1 line at short τ in the measured ADEV and sets the limit below which the comparison cannot see the clocks.' },
  crossover: { short: 'τ at which the device\'s ADEV rises above the reference\'s', long: 'When a local oscillator is disciplined to a reference (GPSDO, steered RAFS), the reference is noisy at short τ and the local oscillator is noisy at long τ. The natural loop time constant is where their ADEV curves cross, and the disciplined clock\'s ADEV is roughly the lower envelope of the two. Holdover after losing the reference is the open-loop growth from that point.' },
  knee: { short: 'Where better device noise stops improving steady-state error', long: 'With periodic external fixes, the steady-state post-fix error depends on both the device noise and the fix quality/cadence. Past some device quality the error is fix-limited and a better device buys nothing; conversely, for a given device there is a slowest cadence that still meets the requirement. This is the PDR trade between device grade and fix duty cycle.' },
  percentile: { short: 'Monte Carlo "3σ" is the 99.73rd percentile, not 3×σ', long: 'The envelope is built from the absolute error across many simulated runs. The 68/95/99.7% lines are percentiles of that sample, so non-Gaussian accumulation (flicker is not Gaussian in its integral) shows honestly instead of being hidden by a Gaussian assumption.' },
  confidence: { short: 'Statistical uncertainty of each ADEV point', long: 'Each ADEV point is an estimate from a finite record; long-τ points use few independent samples and are correspondingly uncertain. The band shows an approximate ±1σ interval from the equivalent degrees of freedom. Points beyond about a tenth of the record length are drawn faded and should not be trusted.' },
  driftKnowledge: { short: 'Uncertainty of the drift rate at the last sync', long: 'For a 3-state clock the deterministic aging rate is estimated before launch or at the last sync. What enters the budget over months is not the aging itself but the uncertainty of that estimate, √p33, which produces a time error of √p33·t²/2. Over months this term usually dominates everything else.' },
};

export const REQUIRED_TERMS = Object.keys(GLOSSARY);

export function dfn(term: string, text?: string): HTMLElement {
  const g = GLOSSARY[term];
  const el = document.createElement('dfn');
  el.textContent = text ?? term;
  if (!g) return el;
  el.title = g.short;
  let open: HTMLElement | null = null;
  el.addEventListener('click', () => {
    if (open) { open.remove(); open = null; return; }
    open = document.createElement('div'); open.className = 'gloss'; open.textContent = g.long;
    el.insertAdjacentElement('afterend', open);
  });
  return el;
}
